---
title: "05_community_analysis_16S"
author: "Julian Liber"
date: "2026-09-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tibble)
library(ggplot2)
library(vegan)
library(stringr)
library(readr)
library(measurements)
library(ggforce)
library(plotly)
library(seqinr)
library(tidyr)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

```{r}
otus <- read_table("../16S/16S_otu-table.txt")
tax <- read_delim("../16S/16S_constax_taxonomy.txt",
                  delim = "\t") %>%
  dplyr::select(-Rank_8) %>%
  mutate(across(starts_with("Rank_"), ~ str_remove(.x, "_[1-9]")))
```

```{r}
tax %>%
  group_by(Rank_2) %>%
  summarize(count = n()) -> phylum_sum
phylum_sum
```

```{r}
otus_t <- t(otus[,2:dim(otus)[2]])
head(otus_t)
rownames(otus_t) <- colnames(otus)[2:dim(otus)[2]]
colnames(otus_t) <- otus$Sample
colnames(otus)

otus_t %>%
  as.data.frame() %>%
  rownames_to_column(var = "OTU_ID") %>%
  left_join(tax, by = "OTU_ID") -> comb_otu_16S

comb_otu_16S %>%
  head()
```

```{r}
convert_lat_long <- function(ll_string, index){
  dir_list <- list(N = 1, S = -1, E = 1, W = -1)
  dec_coord_vec <- c()
  coord_vec <- c()
  dir_vec <- c()
  if (is.na(ll_string)){
    return(NA)
  }
  else {
    if (!str_detect(ll_string, ", ")){
      ll_string <- str_replace(ll_string, ",", ", ")
    }
    if (str_detect(ll_string, ".*?\u0081.*")){ # degree sign
      print("Degree unicode")
      ll_string <- str_replace_all(ll_string, "?\u0081", "")
      ll_string <- str_replace_all(ll_string, "'", "")
      str_lat <- unlist(str_split(ll_string, ", "))[1]
      str_long <- unlist(str_split(ll_string, ", "))[2]
      lat <- conv_unit(str_lat, from = "deg_min_sec", to = "dec_deg")
      long <- conv_unit(str_long, from = "deg_min_sec", to = "dec_deg")
      dec_coord_vec <- as.numeric(c(lat, long))
    }
    else if (str_detect(ll_string, "[0-9]{1,3}°[0-9]{1,2}′[0-9]{1,2}″ [N|S]  [0-9]{1,3}°[0-9]{1,2}′[0-9]{1,2}″ [E|W].*")){ # degree sign
      # print("Degree °")
      ll_string <- str_replace_all(ll_string, "°", " ")
      ll_string <- str_replace_all(ll_string, "′", " ")
      ll_string <- str_replace_all(ll_string, '″', " ")
      # print(ll_string)
      str_lat <- str_split_i(ll_string, " [N|S]  ", 1)
      str_long <- str_remove(str_split_i(ll_string," [N|S]  ", 2), " [E|W].*")
      # print(str_lat)
      # print(str_long)
      lat <- conv_unit(str_lat, from = "deg_min_sec", to = "dec_deg")
      long <- conv_unit(str_long, from = "deg_min_sec", to = "dec_deg")
      dec_coord_vec <- as.numeric(c(lat, long))
      lat_dir <- str_extract(ll_string, "[NS]")
      lon_dir <- str_extract(ll_string, "[EW]")
      if (lat_dir == "S"){
        dec_coord_vec[1] <- dec_coord_vec[1]*-1
      }
      if (lat_dir == "W"){
        dec_coord_vec[2] <- dec_coord_vec[2]*-1
      }
      # print(dec_coord_vec)
    }
    else if (str_detect(ll_string, "[0-9]{1,3}°[0-9]{1,2}′[0-9\\.]{1,5}″[N|S], [0-9]{1,3}°[0-9]{1,2}′[0-9\\.]{1,5}″[E|W].*")){ # degree sign
      # print("Degree °")
      ll_string <- str_replace_all(ll_string, "°", " ")
      ll_string <- str_replace_all(ll_string, "′", " ")
      ll_string <- str_replace_all(ll_string, '″', " ")
      # print(ll_string)
      str_lat <- str_split_i(ll_string, "[N|S], ", 1)
      str_long <- str_remove(str_split_i(ll_string,"[N|S], ", 2), "[E|W].*")
      # print(str_lat)
      # print(str_long)
      lat <- conv_unit(str_lat, from = "deg_min_sec", to = "dec_deg")
      long <- conv_unit(str_long, from = "deg_min_sec", to = "dec_deg")
      dec_coord_vec <- as.numeric(c(lat, long))
      lat_dir <- str_extract(ll_string, "[NS]")
      lon_dir <- str_extract(ll_string, "[EW]")
      if (lat_dir == "S"){
        dec_coord_vec[1] <- dec_coord_vec[1]*-1
      }
      if (lat_dir == "W"){
        dec_coord_vec[2] <- dec_coord_vec[2]*-1
      }
      # print(dec_coord_vec)
    }
    else if (str_detect(ll_string, ".*?\u00C1.*")){ # such as "38Á 31.899', -121Á 45.204'"
      ll_string <- str_replace_all(ll_string, "\u00C1", "")
      ll_string <- str_replace_all(ll_string, "'", "")
      str_lat <- unlist(str_split(ll_string, ", "))[1]
      str_long <- unlist(str_split(ll_string, ", "))[2]
      if (str_detect(ll_string, "\\.")){ # degree minute
        lat <- conv_unit(str_lat, from = "deg_dec_min", to = "dec_deg")
        long <- conv_unit(str_long, from = "deg_dec_min", to = "dec_deg")
      }
      else { # degree minute second
        lat <- conv_unit(str_lat, from = "deg_min_sec", to = "dec_deg")
        long <- conv_unit(str_long, from = "deg_min_sec", to = "dec_deg") 
      }
      dec_coord_vec <- as.numeric(c(lat, long))
    }
    else if (! str_detect(ll_string, "\\.")){ 
      # print("No decimals")
      if (str_detect(ll_string, "[NS]\\d")){
        lat_dir <- str_extract(ll_string, "[NS]")
        lon_dir <- str_extract(ll_string, "[EW]")
        ll_split <- str_extract_all(ll_string, "[NSEW]\\d[\\d\\s]*\\d", simplify = T)
        for (i in ll_split){
          coord_str <- str_extract(i, "\\d[\\d\\s]*\\d")
          coord <- conv_unit(coord_str, from = "deg_min_sec", to = "dec_deg")
          dir <- str_extract(i, "[NSEW]")
          if (! is.na(coord)){
            coord_vec <- c(coord_vec, coord)
          }
          if (! is.na(dir)){
            dir_vec <- c(dir_vec, dir)
          }
        }
      }
      else { # string without decimals, like 44 N 83 W
        ll_split <- unlist(str_split(ll_string, "\\s"))
        for (i in ll_split){
          coord <- str_extract(i, "\\d{1,3}")
          dir <- str_extract(i, "[NSEW]")
          if (! is.na(coord)){
            coord_vec <- c(coord_vec, coord)
          }
          if (! is.na(dir)){
            dir_vec <- c(dir_vec, dir)
          }
        }
      }
      for (i in 1:2){
        dec_coord <- dir_list[[dir_vec[i]]]*as.numeric(coord_vec[i])
        dec_coord_vec <- c(dec_coord_vec, dec_coord)
      }
      return(dec_coord_vec[index])
    }
    else if(str_detect(ll_string, "\\.") & ! str_detect(ll_string, "N|S|E|W")) {
      # print("Decimal without directions")
      ll_split <- unlist(str_split(ll_string, "\\s"))
      for (i in ll_split){
        coord <- str_extract(i, "[0-9\\-]{1,4}\\.\\d*")
        if (! is.na(coord)){
          coord_vec <- c(coord_vec, coord)
        }
      }
      return(as.numeric(coord_vec[index]))
    }
    else { # Decimal string like 44.134 N 83.221 W or with directions first
      # print("Decimal with following direction")
      if (str_detect(ll_string, "[NS]\\d")){
        lat_dir <- str_extract(ll_string, "[NS]")
        lon_dir <- str_extract(ll_string, "[EW]")
        ll_split <- str_extract_all(ll_string, "[NSEW]\\d[\\d\\s\\.]*\\d", simplify = T)
        for (i in ll_split){
          coord_str <- str_extract(i, "\\d[\\d\\s\\.]*\\d")
          coord <- conv_unit(coord_str, from = "deg_min_sec", to = "dec_deg")
          dir <- str_extract(i, "[NSEW]")
          if (! is.na(coord)){
            coord_vec <- c(coord_vec, coord)
          }
          if (! is.na(dir)){
            dir_vec <- c(dir_vec, dir)
          }
        }
        for (i in 1:2){
          dec_coord <- dir_list[[dir_vec[i]]]*as.numeric(coord_vec[i])
          dec_coord_vec <- c(dec_coord_vec, dec_coord)
        }
      }
      else {
        ll_split <- unlist(str_split(ll_string, "\\s"))
        for (i in ll_split){
          coord <- str_extract(i, "\\d{1,3}\\.\\d*")
          dir <- str_extract(i, "[NSEW]")
          if (! is.na(coord)){
            coord_vec <- c(coord_vec, coord)
          }
          if (! is.na(dir)){
            dir_vec <- c(dir_vec, dir)
          }
        }
        for (i in 1:2){
          dec_coord <- dir_list[[dir_vec[i]]]*as.numeric(coord_vec[i])
          dec_coord_vec <- c(dec_coord_vec, dec_coord)
        }
      }
    }
    return(dec_coord_vec[index])
  }
}
```

```{r}
sample_info <- read_delim("../metadata/sample_data.txt", delim = "\t")
sample_info$`Lat-Long`

library_names <- read_csv("../16S/SampleReturn_16S.csv") %>%
  mutate(lib_name = str_remove(Primer_ID, "^Kinnex16S_"))
library_names

library_names %>%
  left_join(sample_info %>%
    rowwise() %>%
    mutate(lat = convert_lat_long(`Lat-Long`, 1),
           lon = convert_lat_long(`Lat-Long`, 2)) %>%
    mutate(Sample_Name = str_c(`Sample prefix`, "_", `Sample number`),
           Location = str_split_i(Sample_name_desc, "_", 1)),
    by = "Sample_Name") -> library_data
```

```{r}
row_counts <- rowSums(otus_t)

plant <- sum(row_counts[comb_otu_16S$Rank_4 == "Chloroplast"], na.rm = T)
mito <- sum(row_counts[comb_otu_16S$Rank_5 == "Mitochondria"], na.rm = T)
no_phylum <- sum(row_counts[is.na(comb_otu_16S$Rank_2) | comb_otu_16S$Rank_2 == ""], na.rm = T)

filt_1 <- comb_otu_16S %>%
    filter(!Rank_4 == "Chloroplast",
           !Rank_5 == "Mitochondria",
           !is.na(Rank_2))

reads_input <- row_counts %>% sum(.)
reads_kept <- filt_1 %>% 
  dplyr::select(all_of(otus$Sample)) %>%
  as.matrix(.) %>% sum(.)
print(paste0("Reads input: ", reads_input %>% format(big.mark = ",")))
print(paste0("Reads kept: ", reads_kept %>% sum(.) %>% format(big.mark = ","), " (", round(100*reads_kept/reads_input, 2), "%)"))
print("Reads removed:")
print(paste0("    Plastid: ", plant %>% format(big.mark = ","),
             " (", round(100*plant/reads_input, 2), "%)"))
print(paste0("    Mitochondria: ", mito %>% format(big.mark = ","),
             " (", round(100*mito/reads_input, 2), "%)"))
print(paste0("    No phylum: ", no_phylum %>% format(big.mark = ","),
             " (", round(100*no_phylum/reads_input, 2), "%)"))
```
After filtering based on taxonomy assignment, we keep 88.37% of reads.

```{r}
library_data %>%
  filter(!str_detect(Sample_Name, "^NC25")) %>%
  pull(var = "lib_name") -> control_samples


control_counts <- rowSums(otus_t[,colnames(otus_t) %in% control_samples])

hist(log10(control_counts/row_counts))
sum(control_counts/row_counts > 0.5)
otus_contam <- names(control_counts[control_counts/row_counts > 0.5])

tax %>%
  filter(OTU_ID %in% otus_contam) %>%
  group_by(Rank_6) %>%
  summarize(count = n())
```
There are 34 OTUs for which > 50% of reads are found in the controls. We will remove these from downstream analysis. Bradyrhizobium and Methylobacterium are the most represented in the controls.
```{r}
filt_2 <- filt_1 %>%
  filter(!OTU_ID %in% otus_contam)
```

Only run below code once (it will take a while).
```{r}
filt_otus <- otus[,filt_2$OTU_ID]
r <- 1e3
n <- 1e3
res_mat <- matrix(0, nrow = dim(filt_otus)[1], ncol = dim(filt_otus)[2])
for (i in 1:r){
  res_mat <- res_mat + rrarefy(filt_otus, n)
}
# rowSums(res_mat)

rare_filt_otus <- res_mat/r
rare_filt_otus %>%
  as.data.frame() %>%
  write_csv("../16S/OTU_table_1000rep_rare.csv")
```

```{r}
rare_filt_otus<- read.csv("../16S/OTU_table_1000rep_rare.csv")
rare_filt_otus %>%
  t() %>%
  as.data.frame() -> rare_otus_t

alpha_div_df <- data.frame(lib_name = otus$Sample,
                           Shannon = diversity(rare_filt_otus, index = "shannon"),
                           Inv_Simpson = diversity(rare_filt_otus, index = "invsimpson")) %>%
  left_join(library_data, by = "lib_name")


alpha_div_df %>%
  pivot_longer(cols = Shannon:Inv_Simpson, names_to = "metric", values_to = "Alpha Diversity") %>%
  ggplot(aes(x = Phenotype, y = `Alpha Diversity`, color = Phenotype)) +
  geom_boxplot(outliers = F) +
  geom_jitter(width = 0.2, alpha = 0.6) +
  facet_wrap(~metric, scales = "free_y") +
  theme(axis.text.x = element_text(angle = -40, hjust = 0, vjust = 0.5),
        legend.position = "none") +
  labs(x = "Sample_type") -> g
g
ggsave("../figs/alpha_diversity_bacteria.svg", g, width = 8, height = 4)

alpha_div_df %>%
  filter(!Material %in% c("Plant", "Soil", "Unknown", "Water", NA, "Air")) %>%
  pivot_longer(cols = Shannon:Inv_Simpson, names_to = "metric", values_to = "Alpha Diversity") %>%
  ggplot(aes(x = Material, y = `Alpha Diversity`, color = Material)) +
  geom_boxplot(outliers = F) +
  geom_jitter(width = 0.2, alpha = 0.6) +
  facet_wrap(~metric, scales = "free_y") +
  theme(axis.text.x = element_text(angle = -40, hjust = 0, vjust = 0.5),
        legend.position = "none") +
  labs(x = "Building Material") -> g
g
ggsave("../figs/alpha_diversity_bacteria_material_type.svg", g, width = 8, height = 4)
ggsave("../figs/alpha_diversity_bacteria_material_type.png", g, width = 8, height = 4)

```

```{r}
colnames(rare_otus_t) <- otus$Sample
rare_otus_t %>%
  rownames_to_column(var = "OTU_ID") %>%
  left_join(tax, by = "OTU_ID") -> comb_otu_rare_16S

data.frame(OTU_ID = rownames(rare_otus_t),
           total_reads = rowSums(rare_otus_t)) %>%
  left_join(tax, by = "OTU_ID") %>%
  group_by(Rank_6) %>%
  summarize(gen_total = sum(total_reads)) %>%
  arrange(-gen_total) -> genera_totals

genera_totals %>%
  filter(!is.na(Rank_6)) %>%
  .[1:30,] %>%
  pull(var = "Rank_6")-> top_30_gen
top_30_gen

comb_otu_rare_16S %>%
  filter(!Rank_6 %in% top_30_gen) %>%
  dplyr::select(otus$Sample) %>%
  colSums() %>%
  t() %>% 
  as.data.frame() %>%
  mutate(Rank_6 = "Other") -> other_sums

other_sums

comb_otu_rare_16S %>%
  filter(Rank_6 %in% top_30_gen) %>%
  group_by(Rank_6) %>%
  summarize(across(otus$Sample, ~ sum(.x))) -> gen_sums

palette_31 <- c('#5e0215', '#1d0f6f', '#03149c', '#761c47', '#08926d', '#557741', # Custom color palette for 31 samples
                '#3c16c2', '#98433c', '#c64f11', '#70a228', '#bf8c01', '#1788b3',
                '#79de00', '#8e15b8', '#4c64ae', '#5ce331', '#49e26e', '#fe159a',
                '#c6955d', '#fd8355', '#63b3e1', '#ebd34d', '#a96bfe', '#a3f08d',
                '#c0adb4', '#8dd2c8', '#d8e587', '#d59eed', '#fe71f4', '#b1dcf0',
                '#d8e9c7')

rbind(other_sums[,c("Rank_6", otus$Sample)],
      gen_sums[,c("Rank_6", otus$Sample)]) %>%
  mutate(across(otus$Sample, ~ .x/sum(.x))) %>%
  # view()
  pivot_longer(cols = -Rank_6, names_to = "lib_name", values_to = "abundance") %>%
  left_join(library_data %>% filter(lib_name %in% otus$Sample), by = "lib_name") %>%
  filter(!is.na(`Broad-scope substrate`)) %>%
  mutate(Genus = factor(Rank_6, levels = c("Other", gen_sums$Rank_6))) -> top_gen_bar_data

top_gen_bar_data %>%
  # filter(!is.na(`Broad-scope substrate`)) %>%
  # mutate(Genus = factor(Rank_6, levels = c("Other", gen_sums$Rank_6))) %>%
  ggplot(aes(x = Sample_name_desc, y = abundance, fill = Genus)) +
  geom_col() +
  facet_row(~`Broad-scope substrate`, scales = "free_x", space = "free") +
  scale_fill_manual(values = palette_31) +
  # facet_grid(Phenotype ~ ., scales = "free", space = "free") +
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust = 0.5)) -> g
g

ggsave("../figs/16S_genus_plot.svg", g, width = 20, height = 10)

htmlwidgets::saveWidget(ggplotly(g), "../figs/16S_genus_plot.html")

top_gen_bar_data %>%
  filter(!is.na(Phenotype)) %>%
  plot_ly(x = ~Sample_name_desc,
          y = ~abundance, 
          color = ~Genus,
          type = 'bar',
          colors = palette_31) -> g2
g2 <- g2 %>% layout(yaxis = list(title = 'Abundance'), 
                    barmode = 'stack')
g2 <- g2 + facet_grid(`Broad-scope substrate` ~ ., scales = "free_x")
g2
htmlwidgets::saveWidget(g2, "../figs/16S_genus_plot.html")
```

```{r}
make_MDS_df <- function(rare_otus, library_data, samples, metric, binary = F){
  MDS_dat <- metaMDS(rare_otus, distance = metric, binary = binary) # Calculate NMDS axes, using Jaccard distance
  MDS_points <- MDS_dat$points # Extract coordinates
  MDS_dat_df <- as.data.frame(MDS_points) %>%
  mutate(lib_name = samples)%>%
  left_join(library_data, by = "lib_name") %>%
  return()
}

MDS_data.jac <- make_MDS_df(rare_filt_otus, library_data, otus$Sample, "jaccard")
MDS_data.bray <- make_MDS_df(rare_filt_otus, library_data, otus$Sample, "bray")
MDS_data.sor <- make_MDS_df(rare_filt_otus, library_data, otus$Sample, "bray", binary = T)

MDS_data.jac %>%
  ggplot(aes(x = MDS1, y = MDS2, color = `Broad-scope substrate`, shape = Location)) +
  geom_point() -> g.jac

MDS_data.bray %>%
  ggplot(aes(x = MDS1, y = MDS2, color = `Broad-scope substrate`, shape = Location)) +
  geom_point() -> g.bray

MDS_data.sor %>%
  ggplot(aes(x = MDS1, y = MDS2, color = `Broad-scope substrate`, shape = Location)) +
  geom_point() -> g.sor

ggsave("../figs/16S_NMDS_jaccard.svg", g.jac, width = 8, height = 6)
ggsave("../figs/16S_NMDS_bray-curtis.svg", g.bray, width = 8, height = 6)
ggsave("../figs/16S_NMDS_sor-dice.svg", g.sor, width = 8, height = 6)

```